"use client"
import { createLineDiff, type StagedChange } from '@/lib/staging'
export type PreviewPayload = { mode: 'idle' } | { mode: 'route'; route: string } | { mode: 'html'; html: string; title?: string } | { mode: 'code'; code: string; language: string; title?: string } | { mode: 'doc'; content: string; title?: string } | { mode: 'diff'; staged: StagedChange }
const devices = { desktop: { width: '100%', height: '100%' }, iphone: { width: 430, height: 932 } } as const
export function PreviewSurface(props: { preview: PreviewPayload; device: keyof typeof devices; safeZone: boolean; onDevice(device: keyof typeof devices): void; onMode(mode: PreviewPayload['mode']): void; onRouteOpen(route: string): void; onApply?(): void; onDiscard?(): void }) {
  const { preview, device, safeZone, onDevice, onMode, onRouteOpen, onApply, onDiscard } = props
  const frame = devices[device]
  const renderMain = () => {
    if (preview.mode === 'route') return <iframe title="route-preview" src={preview.route} style={iframeStyle} />
    if (preview.mode === 'html') return <iframe title={preview.title || 'html-preview'} sandbox="allow-scripts allow-same-origin allow-forms" srcDoc={preview.html} style={iframeStyle} />
    if (preview.mode === 'code') return <iframe title={preview.title || 'code-preview'} sandbox="allow-scripts allow-same-origin" srcDoc={buildSandboxDoc(preview.code, preview.language)} style={iframeStyle} />
    if (preview.mode === 'doc') return <pre style={docStyle}>{preview.content}</pre>
    if (preview.mode === 'diff') {
      const lines = createLineDiff(preview.staged.originalContent, preview.staged.nextContent)
      return <div style={{ display: 'grid', gridTemplateColumns: '1fr', height: '100%', background: '#08111c' }}><div style={{ padding: 14, borderBottom: '1px solid rgba(255,255,255,0.08)', display: 'flex', gap: 10 }}><button onClick={onApply} style={actionButton('#16a34a')}>Apply</button><button onClick={onDiscard} style={actionButton('#334155')}>Discard</button><div style={{ color: 'rgba(255,255,255,0.72)', fontSize: 12 }}>{preview.staged.path}</div></div><pre style={diffStyle}>{lines.join('\n')}</pre></div>
    }
    return <div style={{ display: 'grid', placeItems: 'center', height: '100%', color: '#dce8ff' }}><div style={{ maxWidth: 540, padding: 28, borderRadius: 24, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.08)' }}><div style={{ fontSize: 13, opacity: 0.7, marginBottom: 12 }}>Preview Runtime</div><div style={{ fontSize: 24, fontWeight: 800, marginBottom: 10 }}>StreamsAI Preview Ready</div><div style={{ fontSize: 15, lineHeight: 1.7, opacity: 0.86 }}>This panel renders real routes, chat-generated HTML, TSX/JS sandbox previews, documents, and staged diffs inside the active project context.</div></div></div>
  }
  return <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}><div style={{ height: 40, display: 'flex', alignItems: 'center', gap: 8, padding: '0 10px', borderBottom: '1px solid rgba(255,255,255,0.08)', background: '#07101b', flexShrink: 0 }}><Chip active={preview.mode === 'idle'} onClick={() => onMode('idle')}>Preview</Chip><Chip active={preview.mode === 'diff'} onClick={() => onMode('diff')}>Diff</Chip><Chip active={preview.mode === 'doc'} onClick={() => onMode('doc')}>Doc</Chip><Chip active={device === 'desktop'} onClick={() => onDevice('desktop')}>Desktop</Chip><Chip active={device === 'iphone'} onClick={() => onDevice('iphone')}>iPhone 14 Pro Max</Chip><Chip active={safeZone}>Safe Zone</Chip><input defaultValue="/preview" onKeyDown={(e) => { if (e.key === 'Enter') onRouteOpen((e.target as HTMLInputElement).value) }} placeholder="/preview" style={{ marginLeft: 'auto', width: 160, ...miniInput }} /></div><div style={{ flex: 1, minHeight: 0, display: 'grid', placeItems: 'center', background: '#030814', overflow: 'auto' }}><div style={{ width: frame.width, height: frame.height, maxWidth: '100%', maxHeight: '100%', position: 'relative', borderRadius: device === 'iphone' ? 32 : 0, overflow: 'hidden', boxShadow: '0 10px 60px rgba(0,0,0,0.4)', border: '1px solid rgba(255,255,255,0.08)' }}>{renderMain()}{safeZone && device === 'iphone' && <div style={{ position: 'absolute', inset: 16, border: '2px dashed rgba(255,255,255,0.4)', borderRadius: 20, pointerEvents: 'none' }} />}</div></div></div>
}
function buildSandboxDoc(code: string, language: string) { const isComponent = /tsx|jsx/i.test(language); const transformed = code.replace(/export\s+default/g, 'const __DefaultExport ='); return `<!doctype html><html><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><style>html,body,#root{height:100%;margin:0}body{font-family:Inter,system-ui,sans-serif;background:#0f172a;color:#fff}*{box-sizing:border-box}</style><script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script><script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script><script crossorigin src="https://unpkg.com/@babel/standalone/babel.min.js"></script></head><body><div id="root"></div><script type="text/babel" data-presets="${isComponent ? 'typescript,react' : 'typescript'}">${transformed} const root = ReactDOM.createRoot(document.getElementById('root')); try { ${isComponent ? `const Rendered = typeof __DefaultExport !== 'undefined' ? __DefaultExport : (typeof App !== 'undefined' ? App : null); if (!Rendered) throw new Error('No default component export found'); root.render(React.createElement(Rendered));` : `root.render(React.createElement('pre',{style:{padding:'16px',whiteSpace:'pre-wrap'}}, ${JSON.stringify(code)}));`} } catch (error) { root.render(React.createElement('div',{style:{padding:'16px',color:'#fecaca'}}, 'Preview error: ' + error.message)); }</script></body></html>` }
function Chip({ active, onClick, children }: { active: boolean; onClick?: () => void; children: React.ReactNode }) { return <button onClick={onClick} style={{ border: '1px solid rgba(255,255,255,0.12)', background: active ? 'rgba(68,195,166,0.22)' : 'rgba(255,255,255,0.04)', color: '#eff6ff', borderRadius: 999, padding: '5px 10px', fontSize: 12 }}>{children}</button> }
const miniInput: React.CSSProperties = { padding: '7px 9px', borderRadius: 10, background: 'rgba(255,255,255,0.06)', color: '#fff', border: '1px solid rgba(255,255,255,0.08)' }
const iframeStyle: React.CSSProperties = { width: '100%', height: '100%', border: 'none', display: 'block', background: '#fff' }
const docStyle: React.CSSProperties = { width: '100%', height: '100%', margin: 0, padding: 16, overflow: 'auto', background: '#08111c', color: '#dbeafe', whiteSpace: 'pre-wrap' }
const diffStyle: React.CSSProperties = { width: '100%', height: '100%', margin: 0, padding: 16, overflow: 'auto', background: '#08111c', color: '#dbeafe', whiteSpace: 'pre-wrap', lineHeight: 1.6 }
function actionButton(bg: string): React.CSSProperties { return { background: bg, border: 'none', color: '#fff', borderRadius: 10, padding: '8px 12px', fontSize: 12 } }
